package app.drydock.review;

import app.drydock.git.UnifiedDiff;

import org.junit.jupiter.api.Test;

import java.util.ArrayList;
import java.util.List;
import java.util.OptionalInt;

import static org.junit.jupiter.api.Assertions.assertEquals;
import static org.junit.jupiter.api.Assertions.assertFalse;
import static org.junit.jupiter.api.Assertions.assertTrue;

/**
 * What Review infers from a changed file's path alone, and the
 * kind-and-directory clustering it falls back to for sections.
 */
class ChangedPathsTest {

    @Test
    void aPathsKindIsInferredMostSpecificFirst() {
        assertEquals(ChangedPaths.Kind.GENERATED, ChangedPaths.kindOf("web/package-lock.json"));
        assertEquals(ChangedPaths.Kind.GENERATED, ChangedPaths.kindOf("lib/third_party/x/src/test/FooTest.java"));
        assertEquals(ChangedPaths.Kind.TESTS, ChangedPaths.kindOf("app/src/test/java/app/DiffServiceTest.java"));
        assertEquals(ChangedPaths.Kind.CONFIG, ChangedPaths.kindOf("config/app.yaml"));
        assertEquals(ChangedPaths.Kind.CHANGE, ChangedPaths.kindOf("app/src/main/java/app/DiffService.java"));
    }

    /** A vendored test is GENERATED by kind and still a test for ReadingPath's rank. */
    @Test
    void aVendoredTestIsStillATestPath() {
        assertTrue(ChangedPaths.isTestPath("lib/third_party/x/src/test/FooTest.java"));
        assertFalse(ChangedPaths.isTestPath("app/src/main/java/app/DiffService.java"));
    }

    @Test
    void namesAndDirectoriesSplitAtTheLastSlash() {
        assertEquals("src/app", ChangedPaths.directoryOf("src/app/A.java"));
        assertEquals("", ChangedPaths.directoryOf("README.md"));
        assertEquals("A.java", ChangedPaths.fileName("src/app/A.java"));
        assertEquals("README.md", ChangedPaths.fileName("README.md"));
    }

    @Test
    void clustersReadTheProductionChangeFirstAndKeepTestsApart() {
        UnifiedDiff diff = diff(
                file("app/package-lock.json", 1),
                file("app/src/test/java/app/ATest.java", 1),
                file("app/src/main/java/app/A.java", 2),
                file("app/src/main/java/app/B.java", 1));

        List<ChangedPaths.Cluster> clusters = ChangedPaths.clusters(diff);

        assertEquals(List.of(ChangedPaths.Kind.CHANGE, ChangedPaths.Kind.TESTS, ChangedPaths.Kind.GENERATED),
                clusters.stream().map(ChangedPaths.Cluster::kind).toList());
        assertEquals("java/app · 2 files", clusters.get(0).title());
        assertEquals("ATest.java", clusters.get(1).title());
        assertEquals(List.of(HunkIds.hunkId("app/src/main/java/app/A.java", 0),
                        HunkIds.hunkId("app/src/main/java/app/A.java", 1),
                        HunkIds.hunkId("app/src/main/java/app/B.java", 0)),
                clusters.get(0).hunkIds());
    }

    /** A binary or mode-only change has no hunk, so its section names no file for it. */
    @Test
    void aFallbackSectionListsOnlyTheFilesItHasHunksFor() {
        UnifiedDiff diff = diff(file("src/app/A.java", 1), file("src/app/logo.png", 0));

        List<Sections.Section> sections = ChangedPaths.fallbackSections(diff);

        assertEquals(1, sections.size());
        assertEquals("src/app · 2 files", sections.get(0).title());
        assertEquals(List.of("src/app/A.java"), sections.get(0).files());
        assertEquals(List.of(HunkIds.hunkId("src/app/A.java", 0)), sections.get(0).hunkIds());
    }

    private static UnifiedDiff diff(UnifiedDiff.FileDiff... files) {
        return new UnifiedDiff(List.of(files));
    }

    private static UnifiedDiff.FileDiff file(String path, int hunks) {
        List<UnifiedDiff.Hunk> hunkList = new ArrayList<>();
        for (int i = 0; i < hunks; i++) {
            hunkList.add(new UnifiedDiff.Hunk("@@ -1 +1 @@", List.of(
                    new UnifiedDiff.Line(UnifiedDiff.Line.Kind.ADD, OptionalInt.empty(),
                            OptionalInt.of(i + 1), "line"))));
        }
        return new UnifiedDiff.FileDiff(path, "M", hunks, 0, false, false, List.copyOf(hunkList));
    }
}
